import { HTMLComponent, ComponentTree } from './component.ts'

function generateComponent(componentName: keyof HTMLElementTagNameMap): new (children?: string | ComponentTree) => HTMLComponent {
    // @ts-ignore
    return class extends HTMLComponent implements ConcreteComponent {
        constructor(children?: string | ComponentTree) {
            super(children)

            this._setElement(document.createElement(componentName))
        }
    }
}

export const A = generateComponent('a')
export const Abbr = generateComponent('abbr')
export const Address = generateComponent('address')
export const Area = generateComponent('area')
export const Article = generateComponent('article')
export const Aside = generateComponent('aside')
export const Audio = generateComponent('audio')
export const B = generateComponent('b')
export const Base = generateComponent('base')
export const BDI = generateComponent('bdi')
export const Bdo = generateComponent('bdo')
export const BlockQuote = generateComponent('blockquote')
export const Body = generateComponent('body')
export const BR = generateComponent('br')
export const Button = generateComponent('button')
export const Canvas = generateComponent('canvas')
export const Caption = generateComponent('caption')
export const Cite = generateComponent('cite')
export const Code = generateComponent('code')
export const Col = generateComponent('col')
export const ColGroup = generateComponent('colgroup')
export const Data = generateComponent('data')
export const DataList = generateComponent('datalist')
export const DD = generateComponent('dd')
export const Del = generateComponent('del')
export const Details = generateComponent('details')
export const DFN = generateComponent('dfn')
export const Dialog = generateComponent('dialog')
export const Div = generateComponent('div')
export const DL = generateComponent('dl')
export const DT = generateComponent('dt')
export const EM = generateComponent('em')
export const Embed = generateComponent('embed')
export const FieldSet = generateComponent('fieldset')
export const FigCaption = generateComponent('figcaption')
export const Figure = generateComponent('figure')
export const Footer = generateComponent('footer')
export const Form = generateComponent('form')
export const Head = generateComponent('head')
export const Header = generateComponent('header')
export const HGroup = generateComponent('hgroup')
export const H1 = generateComponent('h1')
export const H2 = generateComponent('h2')
export const H3 = generateComponent('h3')
export const H4 = generateComponent('h4')
export const H5 = generateComponent('h5')
export const H6 = generateComponent('h6')
export const HR = generateComponent('hr')
export const HTML = generateComponent('html')
export const I = generateComponent('i')
export const IFrame = generateComponent('iframe')
export const Input = generateComponent('input')
export const Img = generateComponent('img')
export const Ins = generateComponent('ins')
export const KBD = generateComponent('kbd')
export const Label = generateComponent('label')
export const Link = generateComponent('link')
export const Legend = generateComponent('legend')
export const LI = generateComponent('li')
export const Main = generateComponent('main')
export const Map = generateComponent('map')
export const Mark = generateComponent('mark')
export const Menu = generateComponent('menu')
export const Meta = generateComponent('meta')
export const Meter = generateComponent('meter')
export const Nav = generateComponent('nav')
export const NoScript = generateComponent('noscript')
export const Object = generateComponent('object')
export const OL = generateComponent('ol')
export const OptGroup = generateComponent('optgroup')
export const Option = generateComponent('option')
export const P = generateComponent('p')
export const Param = generateComponent('param')
export const Picture = generateComponent('picture')
export const Pre = generateComponent('pre')
export const Progress = generateComponent('progress')
export const Q = generateComponent('q')
export const RP = generateComponent('rp')
export const RT = generateComponent('rt')
export const Ruby = generateComponent('ruby')
export const S = generateComponent('s')
export const Samp = generateComponent('samp')
export const Section = generateComponent('section')
export const Select = generateComponent('select')
export const Small = generateComponent('small')
export const Source = generateComponent('source')
export const Span = generateComponent('span')
export const Strong = generateComponent('strong')
export const Sub = generateComponent('sub')
export const Summary = generateComponent('summary')
export const Sup = generateComponent('sup')
export const Table = generateComponent('table')
export const TBody = generateComponent('tbody')
export const TD = generateComponent('td')
export const Template = generateComponent('template')
export const TextArea = generateComponent('textarea')
export const TFoot = generateComponent('tfoot')
export const TH = generateComponent('th')
export const THead = generateComponent('thead')
export const Time = generateComponent('time')
export const Title = generateComponent('title')
export const TR = generateComponent('tr')
export const Track = generateComponent('track')
export const U = generateComponent('u')
export const UL = generateComponent('ul')
export const Var = generateComponent('var')
export const Video = generateComponent('video')
export const WBR = generateComponent('wbr')
